const deck = {
    name: 'Top 100 spanish words',
    description: 'These 100 words make 50% of the commonly spoken spanish',
    cards: [
        { q: 'the', a:'el / la (def. art.)' },
        { q: 'of, from', a:'de (prep.)' },
        { q: 'that, which', a:'que (conj.)' },
        { q: 'and', a:'y (conj.)' },
        { q: 'to, at', a:'a (prep.)' },
        { q: 'in, on', a:'en (prep.)' },
        { q: 'a, an', a:'un (indef. art.)' },
        { q: 'to be', a:'ser (verb)' },
        { q: '-self, oneself [reflexive marker]', a:'se (pron.)' },
        { q: 'no', a:'no (adv.)' },
        { q: 'to have', a:'haber (verb)' },
        { q: 'by, for, through', a:'por (prep.)' },
        { q: 'with ', a:'con (prep.)' },
        { q: 'his, her, their, your (fam.)', a:'su (adj.)' },
        { q: 'for, to, in order to', a:'para (prep.)' },
        { q: 'like, as', a:'como (conj.)' },
        { q: 'to be', a:'estar (verb)' },
        { q: 'to have', a:'tener (verb)' },
        { q: '[3rd pers. indirect object pronoun]', a:'le (pron.)' },
        { q: 'the (+ noun)', a:'lo (art.)' },
        { q: '[3rd pers. masc. direct object pronoun]', a:'lo (pron.)' },
        { q: 'all, every', a:'todo (adj.)' },
        { q: 'but, yet, except ', a:'pero (conj.)' },
        { q: 'more', a:'más (adj.)' },
        { q: 'to do, make', a:'hacer (verb.)' },
        { q: 'or', a:'o (conj.)' },
        { q: 'to be able to, can ', a:'poder (verb)' },
        { q: 'to tell, say', a:'decir (verb)' },
        { q: 'this (m); esta (f)', a:'este (adj.)' },
        { q: 'to go ', a:'ir (verb)' },
        { q: 'other, another', a:'otro (adj.)' },
        { q: 'that (m); esa (f)', a:'ese (adj.)' },
        { q: '[3rd pers. fem. direct object pronoun]', a:'la (pron.)' },
        { q: 'if, whether', a:'si (conj.)' },
        { q: 'me ', a:'me (pron.)' },
        { q: 'already, still', a:'ya (adv.)' },
        { q: 'to see', a:'ver (verb)' },
        { q: 'because', a:'porque (conj.)' },
        { q: 'to give', a:'dar (verb)' },
        { q: 'when ', a:'cuando (conj.)' },
        { q: 'he', a:'él (pron.)' },
        { q: 'very, really', a:'muy (adv.)' },
        { q: 'without', a:'sin (prep.)' },
        { q: 'time, occurrence ', a:'vez (noun, f.)' },
        { q: 'much, many, a lot', a:'mucho (adj.)' },
        { q: 'to know', a:'saber (verb)' },
        { q: 'what?, which?, how (+ adj.)', a:'qué (pron.)' },
        { q: 'on top of, over, about', a:'sobre (prep.)' },
        { q: 'my', a:'mi (adj.)' },
        { q: 'some; (pron.) someone', a:'alguno (adj.)' },
        { q: 'same', a:'mismo (adj.)' },
        { q: 'I', a:'yo (pron.)' },
        { q: 'also', a:'también (adv.)' },
        { q: 'until, up to; (adv.) even', a:'hasta (prep.)' },
        { q: 'year', a:'año (noun, m.)' },
        { q: 'two', a:'dos (num.)' },
        { q: 'to want, love', a:'querer (verb)' },
        { q: 'between', a:'entre (prep.)' },
        { q: 'like that', a:'así (adv.)' },
        { q: 'first', a:'primero (adj.)' },
        { q: 'from, since', a:'desde (prep.)' },
        { q: 'large, great, big', a:'grande (adj.)' },
        { q: 'that', a:'eso (pron., n.)' },
        { q: 'not even, neither, nor ', a:'ni (conj.)' },
        { q: 'us', a:'nos (pron.)' },
        { q: 'to arrive', a:'llegar (verb)' },
        { q: 'to pass, spend (time)', a:'pasar (verb)' },
        { q: 'time, weather', a:'tiempo (noun, m.)' },
        { q: 'she; ellas them', a:'ella (pron.)' },
        { q: 'yes', a:'sí (adv.)' },
        { q: 'day', a:'día (noun, m.)' },
        { q: 'one', a:'uno (num.)' },
        { q: 'well', a:'bien (adv.)' },
        { q: 'little few; (adv.) a little bit', a:'poco (adj.)' },
        { q: 'should, ought to; to owe', a:'deber (verb)' },
        { q: 'so, then', a:'entonces (adv.)' },
        { q: 'to put (on); get (+ adj.)', a:'poner (verb)' },
        { q: 'thing', a:'cosa (noun, f.)' },
        { q: 'much', a:'tanto (adj.)' },
        { q: 'man, mankind, husband', a:'hombre (noun, m.)' },
        { q: 'to seem, look like', a:'parecer (verb)' },
        { q: 'our', a:'nuestro (adj.)' },
        { q: 'such, a, too, so', a:'tan (adv.)' },
        { q: 'where ', a:'donde (conj.)' },
        { q: 'now', a:'ahora (adv.)' },
        { q: 'part, portion', a:'parte (noun, f.)' },
        { q: 'after', a:'después (adv.)' },
        { q: 'life', a:'vida (noun, f.)' },
        { q: 'to remain, stay', a:'quedar (verb)' },
        { q: 'always', a:'siempre (adv.)' },
        { q: 'to believe', a:'creer (verb)' },
        { q: 'to speak, talk', a:'hablar (verb)' },
        { q: 'to take, carry', a:'llevar (verb)' },
        { q: 'to let, leave ', a:'dejar (verb)' },
        { q: 'nothing', a:'nada (pron.)' },
        { q: 'each, every', a:'cada (adj.)' },
        { q: 'to follow', a:'seguir (verb)' },
        { q: 'less, fewer', a:'menos (adj.)' },
        { q: 'new', a:'nuevo (adj.)' },
        { q: 'to find', a:'encontrar (verb)' },
    ]
};

export default deck;
